feat: add aldhair-vera.md
makeitrealcamp/top-v11 pull request #3
Opened 2021-11-18 00:58 UTC by BurningAl15

### Description
Add aldhair-vera.md file

### Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [x] 🤙 Quick Fix
- [ ] 👌 Implented, Tested and Done
- [ ] 🤞 I really hope this works, please review it

### Ticket (Issue Tracking)
CV-13

### Scope
- [ ] 🐞 Bugfix (non-breaking changes to fix a bug)
- [ ] 💚 Enhancement (non-breaking change to add/modify functionality to an existing feature)
- [x] ⚡️ Feature (non-breaking change to add a new feature)
- [ ] ⚠️ Breaking change (change that is not backward compatible, changes to current functionality)
̌

2021-11-18 23:21 UTC, pablovem requested changes

2021-11-18 23:21 UTC, pablovem commented on README.md
> +13. [Aldhair Vera](profiles/aldhair-vera.md)
Please remove changes in this file.

2021-11-18 23:21 UTC, pablovem commented on profiles/aldhair-vera.md
> +- [LinkTree] https://linktr.ee/aldhairvera
Please fix this link.

2021-11-18 23:25 UTC, BurningAl15 commented on profiles/aldhair-vera.md
> +- [LinkTree] https://linktr.ee/aldhairvera
Link fixed.

2021-11-18 23:26 UTC, BurningAl15 commented on README.md
> +13. [Aldhair Vera](profiles/aldhair-vera.md)
Change removed in file.

2021-11-19 00:07 UTC, pablovem approved these changes
LGTM!

2021-11-19 00:07 UTC, saradvr approved these changes

2021-11-19 00:12 UTC, merged